# Frutiger Aero - a drop-in theme module.
#
# This is the ONLY file that knows anything about how the system looks. It is a
# normal NixOS module: configuration.nix just lists it in `imports`, and
# removing that one line reverts the machine to its untouched appearance.
#
# It overrides what configuration.nix already sets (icons, GTK theme, cursor,
# the kitty and dunst palettes, the zsh prompt) with lib.mkForce, and adds what
# it does not (fonts, the gloss CSS, and the colour files that the raw
# hyprland/waybar/rofi dotfiles import).
#
# The palette block is GENERATED by assets/gen-palette.py from the current
# wallpaper. Re-run that script after changing the wallpaper; do not edit
# between the markers by hand.

{ config, pkgs, lib, ... }:

let
	#	=== BEGIN GENERATED PALETTE - assets/gen-palette.py ===
	palette	= {
		abyss	= "040405";	# surface
		deep	= "090b0d";	# surface
		mid	= "13171b";	# surface

		# --- accents ---
		coral	= "ff6166";	# fallback (hue absent from wallpaper)
		sun	= "ffeb61";	# wallpaper (1025 px, drift +7deg -> 52deg)
		grass	= "87c944";	# wallpaper (176 px, drift -12deg -> 90deg)
		mint	= "3ddbc9";	# wallpaper (3854 px, drift +23deg -> 173deg)
		aqua	= "009ed9";	# wallpaper (27699 px, drift +6deg -> 196deg)
		sky	= "0055e8";	# wallpaper, but pushed back to target 218deg (was within 14deg of the previous accent)
		violet	= "d47dff";	# fallback (hue absent from wallpaper)

		foam	= "e6e3d5";	# foreground
		gloss	= "fffdf0";	# bright text / highlight
		rim	= "fffcec";	# gloss rim highlight
		inactive	= "54606b";	# dimmed foreground
	};
	#	=== END GENERATED PALETTE ===

	aero	= palette;

	#	Nix only strips *space* indentation from '' strings, and this file is
	#	tab-indented, so generated files would keep their leading tabs.
	#	Strip up to three tabs per line, preserving relative nesting.
	unindent	= s:
		let
			dedent	= l: pkgs.lib.removePrefix "\t"
									(pkgs.lib.removePrefix "\t"
										(pkgs.lib.removePrefix "\t" l));
		in pkgs.lib.concatStringsSep "\n" (map dedent (pkgs.lib.splitString "\n" s));

	#	Hex -> "r;g;b" for the 24-bit terminal escapes the zsh prompt uses,
	#	so the prompt is driven by palette.nix like everything else.
	hexNib	= c: {
		"0"=0; "1"=1; "2"=2; "3"=3; "4"=4; "5"=5; "6"=6; "7"=7;
		"8"=8; "9"=9; "a"=10; "b"=11; "c"=12; "d"=13; "e"=14; "f"=15;
	}.${pkgs.lib.toLower c};
	hexByte	= s2: 16 * (hexNib (builtins.substring 0 1 s2)) + hexNib (builtins.substring 1 1 s2);
	rgb			= h: "${toString (hexByte (builtins.substring 0 2 h))};"
							+ "${toString (hexByte (builtins.substring 2 2 h))};"
							+ "${toString (hexByte (builtins.substring 4 2 h))}";

	#	Frutiger Aero zsh prompt. Two lines like the "bira" theme it replaces,
	#	but recoloured to the palette: a dark frame, an aqua bubble marker, the
	#	path in sky blue, git state in green/amber, and a caret that turns coral
	#	when the last command failed.
	aero-zsh-theme	= pkgs.runCommand "frutiger-aero-zsh-theme" { } ''
		mkdir -p $out/themes
		#	<<- strips leading TABS, which is what keeps this readable inside a
		#	tab-indented Nix file and still emits the theme at column 0.
		cat > $out/themes/frutiger-aero.zsh-theme <<-'THEME'
		#	Frutiger Aero prompt. Generated from palette.nix - do not edit.
		#	These must be global, not local: oh-my-zsh runs with prompt_subst,
		#	so PROMPT is single-quoted and the colours are expanded on every
		#	redraw rather than once at source time.
		typeset -g _aero_fg=$'\e[38;2;'
		typeset -g AERO_RESET="%{''${_aero_fg}${rgb aero.foam}m%}"
		typeset -g AERO_FRAME="%{''${_aero_fg}${rgb aero.inactive}m%}"
		typeset -g AERO_AQUA="%{''${_aero_fg}${rgb aero.aqua}m%}"
		typeset -g AERO_SKY="%{''${_aero_fg}${rgb aero.sky}m%}"
		typeset -g AERO_GRASS="%{''${_aero_fg}${rgb aero.grass}m%}"
		typeset -g AERO_SUN="%{''${_aero_fg}${rgb aero.sun}m%}"
		typeset -g AERO_CORAL="%{''${_aero_fg}${rgb aero.coral}m%}"
		typeset -g AERO_GLOSS="%{''${_aero_fg}${rgb aero.gloss}m%}"

		ZSH_THEME_GIT_PROMPT_PREFIX="''${AERO_FRAME}  ''${AERO_GRASS}"
		ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
		ZSH_THEME_GIT_PROMPT_DIRTY="''${AERO_SUN} ●"
		ZSH_THEME_GIT_PROMPT_CLEAN="''${AERO_AQUA} ●"

		PROMPT='$AERO_FRAME╭─ $AERO_AQUA◍ $AERO_GLOSS%n $AERO_FRAME $AERO_SKY%~$(git_prompt_info)
		$AERO_FRAME╰─%(?.$AERO_AQUA.$AERO_CORAL)❯$AERO_RESET '
		RPROMPT=""
		THEME
	'';

	# Oxygen is the genuine KDE4-era glossy icon set, but it predates every
	# modern app: firefox, code, thunar, kitty, vlc all resolve to nothing, so
	# it needs a chain behind it. The ORDER is what makes app icons match the
	# glossy system icons instead of clashing with them:
	#
	#   la-capitaine  skeuomorphic app icons with real depth and gradients -
	#                 the closest packaged match to Oxygen's look (29 of 64
	#                 menu entries here)
	#   hicolor       each app's own shipped logo, full-colour and detailed (27)
	#   Papirus       flat, matte, clashes - so it sits LAST and only catches
	#                 the 5 names nothing else has
	oxygen-aero	= pkgs.runCommand "oxygen-icons-aero" { } ''
		mkdir -p $out/share/icons
		cp -r ${pkgs.kdePackages.oxygen-icons}/share/icons/oxygen $out/share/icons/
		chmod -R u+w $out/share/icons/oxygen
		sed -i 's/^Inherits=.*/Inherits=la-capitaine-icon-theme,hicolor,Papirus-Dark,Papirus/' \
			$out/share/icons/oxygen/index.theme
		${pkgs.gtk3}/bin/gtk-update-icon-cache -f -t $out/share/icons/oxygen || true
	'';

	graphite-aero	= pkgs.graphite-gtk-theme.override {
		themeVariants	= [ "blue" ];
		colorVariants	= [ "dark" ];
		tweaks				= [ "darker" ];
	};

	#	Gloss layered over Graphite. Colours come from ~/.config/theme/colors.css,
	#	which is generated below from palette.nix, so this stays in sync.
	aeroGtkCss	= unindent ''
		@import url("file:///home/fede/.config/theme/colors.css");

		headerbar, .titlebar {
			background-image: linear-gradient(to bottom,
				alpha(@aero_rim, 0.22)  0%,
				alpha(@aero_mid, 0.96) 48%,
				alpha(@aero_deep, 0.98) 52%,
				alpha(@aero_deep, 0.94) 100%);
			box-shadow: inset 0 1px 0 alpha(@aero_rim, 0.45);
		}

		button {
			background-image: linear-gradient(to bottom,
				alpha(@aero_rim, 0.18)  0%,
				alpha(@aero_mid, 0.90) 48%,
				alpha(@aero_deep, 0.95) 52%,
				alpha(@aero_deep, 0.90) 100%);
			box-shadow: inset 0 1px 0 alpha(@aero_rim, 0.35);
		}

		button:hover {
			box-shadow: inset 0 1px 0 alpha(@aero_rim, 0.60),
			            0 0 8px alpha(@aero_aqua, 0.35);
		}

		button:checked, button:active {
			background-image: linear-gradient(to bottom,
				alpha(@aero_aqua, 0.75)  0%,
				alpha(@aero_sky, 0.90)  48%,
				alpha(@aero_sky, 0.95)  52%,
				alpha(@aero_sky, 0.85) 100%);
		}

		entry {
			box-shadow: inset 0 1px 3px alpha(@aero_abyss, 0.60),
			            inset 0 -1px 0 alpha(@aero_rim, 0.18);
		}

		entry:focus {
			box-shadow: inset 0 1px 3px alpha(@aero_abyss, 0.60),
			            0 0 6px alpha(@aero_aqua, 0.45);
		}

		progressbar progress, scale highlight {
			background-image: linear-gradient(to bottom,
				alpha(@aero_rim, 0.55) 0%, @aero_aqua 48%, @aero_sky 52%, @aero_sky 100%);
		}
	'';

	#	Every colour the module writes out, in one place.
	colorsConf	= unindent ''
			# Generated from palette.nix - do not edit by hand.
			$aeroAbyss = rgb(${aero.abyss})
			$aeroDeep  = rgb(${aero.deep})
			$aeroMid   = rgb(${aero.mid})
			$aeroRim   = rgb(${aero.rim})
			$aeroAqua  = rgb(${aero.aqua})
			$aeroSky   = rgb(${aero.sky})
			$aeroGrass = rgb(${aero.grass})
			$aeroMint  = rgb(${aero.mint})
			$aeroViolet = rgb(${aero.violet})
			$aeroFoam  = rgb(${aero.foam})
			$aeroGloss = rgb(${aero.gloss})
			$aeroCoral = rgb(${aero.coral})
			$aeroSun   = rgb(${aero.sun})

			# ready-made values: hyprland.conf then holds no colours of its own
			$aeroActiveBorder = rgba(${aero.coral}ee) rgba(${aero.sun}ee) rgba(${aero.grass}ee) rgba(${aero.aqua}ee) rgba(${aero.sky}ee) 45deg
			$aeroInactiveBorder = rgba(${aero.mid}99)
			$aeroShadow = rgba(${aero.abyss}dd)
			$aeroShadowInactive = rgba(${aero.abyss}99)
	'';

	colorsCss	= unindent ''
			/* Generated from palette.nix - do not edit by hand. */
			@define-color aero_abyss #${aero.abyss};
			@define-color aero_deep  #${aero.deep};
			@define-color aero_mid   #${aero.mid};
			@define-color aero_rim   #${aero.rim};
			@define-color aero_aqua  #${aero.aqua};
			@define-color aero_sky   #${aero.sky};
			@define-color aero_grass #${aero.grass};
			@define-color aero_mint  #${aero.mint};
			@define-color aero_violet #${aero.violet};
			@define-color aero_foam  #${aero.foam};
			@define-color aero_gloss #${aero.gloss};
			@define-color aero_coral #${aero.coral};
			@define-color aero_sun   #${aero.sun};
			@define-color aero_inactive #${aero.inactive};
	'';

	colorsRasi	= unindent ''
			/* Generated from palette.nix - do not edit by hand. */
			* {
				aero-abyss:	#${aero.abyss}ff;
				aero-deep:	#${aero.deep}ff;
				aero-mid:		#${aero.mid}ff;
				aero-rim:		#${aero.rim}ff;
				aero-aqua:	#${aero.aqua}ff;
				aero-sky:		#${aero.sky}ff;
				aero-grass:	#${aero.grass}ff;
				aero-mint:	#${aero.mint}ff;
				aero-violet:	#${aero.violet}ff;
				aero-foam:	#${aero.foam}ff;
				aero-gloss:	#${aero.gloss}ff;
				aero-coral:	#${aero.coral}ff;
				aero-sun:		#${aero.sun}ff;
				aero-inactive:	#${aero.inactive}ff;

				/* ready-made surfaces: the rofi theme then holds no hexes */
				aero-bg:			#${aero.deep}f7;
				aero-bg-alt:		#${aero.abyss}e6;
				aero-bg-sec:		#${aero.mid}ff;
				aero-rim-soft:		#${aero.rim}26;
				aero-rim-strong:	#${aero.rim}59;
				aero-glass-panel:	linear-gradient(160deg, #${aero.mid}f2, #${aero.abyss}fc);
				aero-glass-raised:	linear-gradient(0, #${aero.deep}ff, #${aero.mid}ff);
				aero-glass-sunken:	linear-gradient(0, #${aero.abyss}f2, #${aero.deep}f2);
				aero-glass-selected:	linear-gradient(0, #${aero.coral}d9, #${aero.sun}cc, #${aero.grass}cc, #${aero.sky}cc);
				aero-highlight:		#${aero.violet}33;
			}
	'';

	force	= lib.mkForce;
in
{
	#	--- system level ------------------------------------------------------
	fonts.packages	= with pkgs; [
		#	Frutiger and Myriad Pro are the real Aero faces and are non-free;
		#	Source Sans is the closest humanist stand-in and Open Sans covers
		#	the Segoe UI role.
		source-sans-pro
		open-sans
	];

	environment.systemPackages = [
		oxygen-aero						# glossy KDE4-era icons + the fallback chain
		pkgs.la-capitaine-icon-theme	# skeuomorphic app icons (see oxygen-aero)
		pkgs.papirus-icon-theme			# last-resort fallback in that chain
	];

	programs.zsh.ohMyZsh	= {
		theme	= force "frutiger-aero";
		custom	= "${aero-zsh-theme}";
	};

	#	--- user level --------------------------------------------------------
	home-manager.users.fede	= {
		home.pointerCursor	= {
			name		= force "Bibata-Modern-Ice";
			package	= force pkgs.bibata-cursors;
		};

		gtk	= {
			cursorTheme.name	= force "Bibata-Modern-Ice";
			iconTheme	= {
				name		= force "oxygen";
				package	= force oxygen-aero;
			};
			theme	= {
				name		= force "Graphite-blue-Dark";
				package	= force graphite-aero;
			};
			gtk4.theme	= {
				name		= force "Graphite-blue-Dark";
				package	= force graphite-aero;
			};

			#	Graphite is flat by design; the gloss is layered on here. The hard
			#	48%/52% stop in each gradient is the Aero trick - a soft gradient
			#	reads as a plastic button, a hard mid-stop reads as glass.
			gtk3.extraCss	= aeroGtkCss;
			gtk4.extraCss	= aeroGtkCss;
		};

		#	The palette, exported for the raw dotfiles. hyprland, waybar and rofi
		#	each import the file in their own syntax, so their live-edit symlinks
		#	keep working: only a palette change needs a rebuild.
		home.file.".config/theme/colors.conf".text	= colorsConf;
		home.file.".config/theme/colors.css".text	= colorsCss;
		home.file.".config/theme/colors.rasi".text	= colorsRasi;

		programs.kitty.settings	= {
			active_tab_foreground		= force "#${aero.abyss}";
			active_tab_background		= force "#${aero.aqua}";
			inactive_tab_foreground	= force "#${aero.inactive}";
			inactive_tab_background	= force "#${aero.deep}";
			tab_bar_background			= force "#${aero.abyss}";

			#	let Hyprland's blur show through the glass
			background_opacity	= "0.88";
			background_blur			= 1;

			background						= force "#${aero.abyss}";
			foreground						= force "#${aero.foam}";
			cursor								= force "#${aero.aqua}";
			selection_background	= force "#${aero.mid}";

			color0	= force "#${aero.deep}";
			color1	= force "#${aero.coral}";
			color2	= force "#${aero.grass}";
			color3	= force "#${aero.sun}";
			color4	= force "#${aero.sky}";
			color5	= force "#${aero.violet}";
			color6	= force "#${aero.aqua}";
			color7	= force "#a4c8dd";

			color8	= force "#${aero.inactive}";
			color9	= force "#ff88a0";
			color10	= force "#9ee85f";
			color11	= force "#ffe08a";
			color12	= force "#4fc8ff";
			color13	= force "#c99dff";
			color14	= force "#5cf5f0";
			color15	= force "#${aero.gloss}";
		};

		services.dunst.settings	= {
			global	= {
				corner_radius	= force 16;
				highlight			= force "#${aero.aqua}";
				icon_theme		= force "oxygen,Papirus-Dark";
				font					= force "Open Sans Semibold 11";
			};

			urgency_low	= {
				background	= force "#${aero.deep}e6";
				foreground	= force "#${aero.inactive}";
				frame_color	= force "#${aero.sky}";
			};

			urgency_normal	= {
				background	= force "#${aero.deep}e6";
				foreground	= force "#${aero.foam}";
				frame_color	= force "#${aero.aqua}";
			};

			urgency_critical	= {
				background	= force "#${aero.abyss}f2";
				foreground	= force "#${aero.foam}";
				frame_color	= force "#${aero.coral}";
			};
		};
	};
}
