monitor=,1920x1080@60,0x0,1.5
monitor = HDMI-A-1, 2560x1440@144, -1600x-550, 1.6
workspace = 1,  monitor:eDP-1,    default:true
workspace = 2,  monitor:eDP-1
workspace = 3,  monitor:eDP-1
workspace = 4,  monitor:eDP-1
workspace = 5,  monitor:eDP-1
workspace = 6,  monitor:HDMI-A-1, default:true
workspace = 7,  monitor:HDMI-A-1
workspace = 8,  monitor:HDMI-A-1
workspace = 9,  monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1